<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Begin Jekyll SEO tag v2.7.1 -->
<title>Portfolio | Aashima Ahuja</title>
<meta name="generator" content="Jekyll v3.9.0" />
<meta property="og:title" content="Portfolio" />
<meta property="og:locale" content="en_US" />
<meta name="description" content="Server Administrator aniljahangir8@gmail.com LinkedIn Profile Github" />
<meta property="og:description" content="Server Administrator aniljahangir8@gmail.com LinkedIn Profile Github" />
<link rel="canonical" href="https://aniljahangir8.github.io/" />
<meta property="og:url" content="https://aniljahangir8.github.io/" />
<meta property="og:site_name" content="Anil Jahangir" />
<meta name="twitter:card" content="summary" />
<meta property="twitter:title" content="Portfolio" />
<script type="application/ld+json">
{"publisher":{"@type":"Organization","logo":{"@type":"ImageObject","url":"https://aashimaahuja.github.io/profile-pic.jpg?raw=true"}},"description":"Server Administrator aniljahangir8@gmail.com LinkedIn Profile Github","url":"https://aniljahangir8.github.io/","@type":"WebSite","headline":"Portfolio","name":"Anil Jahangir","@context":"https://schema.org"}</script>
<!-- End Jekyll SEO tag -->

    <link rel="stylesheet" href="/assets/css/style.css?v=ff0e4d3220c2e19afe3436a9972b83000f1aeaf4">
    <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->
    <!-- start custom head snippets, customize with your own _includes/head-custom.html file -->

<!-- Setup Google Analytics -->



<!-- You can set your favicon here -->
<!-- link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" -->

<!-- end custom head snippets -->
